# Default values for server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "satpolpp"
fullnameOverride: ""

image:
  repository: imrenagi/satpol-pp:latest

certs:
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lSQU9rODJHNnVSS3hIRGZVNGZualpNUzB3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa01qWXhZamN6TkdFdFlUVTBaUzAwWVRnMExUZzJabUV0T0dNek1qUmhOakl3T1dFMwpNQjRYRFRJd01EZ3lNREF5TkRneE4xb1hEVEkxTURneE9UQXpORGd4TjFvd0x6RXRNQ3NHQTFVRUF4TWtNall4CllqY3pOR0V0WVRVMFpTMDBZVGcwTFRnMlptRXRPR016TWpSaE5qSXdPV0UzTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBby9PZ01wTGE0eUFRU01zUjZpLzhPZG9nQmdKL0NGeG1GU1ZtdFdUUAphUkZiVGZEaHVYS0FFbDUvdTJpbjQ5SkZNVVVVaVc4MlMyai9CZjdsZlNvU1h0bU5hVlQ2c2JxWjVuM0cyajJ6CkczbnAyS284L2xGc0kwM3ZmUVdpV2dPK3ZzYmdsWW9PbXpwbmJuMUp5MVpYVm10NnlQOUVrT0RFRjZCY1ZBenEKWDdDWUp2cENGekhXbHI0aUdvTVBuTWFnK0FQWDdaaFE4VllHaFJZWUFLc3g5UGtGYklSZmhBemk3blYwdWVGMQpkVmd2YldCKzFZbW9IYTRuWUtCOEVsL0lublA3YlRXZXMwY25LR2pKK2hXTElBejRsMnAzelYwRGRNaVZhQ1dhCmx4d3huSVg2bnpCWlJzYndXckFFNVg1c0p5L3FmSmY3cWxaUFJ0dEN2eEJQOVFJREFRQUJvMEl3UURBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXhlMXBxUnM3aWlDdgpsZmlER1Q0R1VCLytKMFF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUQ1dlNxSW8wYXkzUkdwLzBkaVpSV2g2CndlcjhtZnJSa2dpbkl1ZUJSK2FKL1U2eFVMSit6N1dCRGFRdWlyV3F4RFBQTXZnenBObGd1dnk5RGdGb2FSQVYKc0VkcmZYbkkwSjV4OUlLSHRsUGFzS0I0c3JlVnI1RnlmaEVTWVN3eGxuV0VXZ0IzWkFORHhqdGZLK0o0Z2t0VgpDZU5HcFpySmxESy8ycVFSaTZXMG1MWUZFOWlSbmhCWk5oUkkzbWJDM3J4SXZ2Tk1NcXBXOFRnZkE1K3pnNjVVCkJjREZWMTg2UDkwc3hlZHU5OFp0SUFwaHloaCtEZG0vTnU0WHora0RlV3BEMU1uLzFIUXNFeVQ2Y0lzRk5vekQKUHF1KzVaR0YzcnVuRURSM1ZjZE5FTjRUcjhaUlpsd2VuREJqWmFhdHR2Vmw2bXAxU3BzSHZocWVmZTZtaW5zPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

serviceAccount:
  create: true
  name:

resources: 
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi