apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satpolpp.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "satpolpp.name" . }}
    helm.sh/chart: {{ include "satpolpp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "satpolpp.name" . }}    
      app.kubernetes.io/instance: {{ .Release.Name }}    
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "satpolpp.name" . }}
        helm.sh/chart: {{ include "satpolpp.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ include "satpolpp.serviceAccountName" . }}
      containers:
      - name: satpolpp
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SATPOLPP_AUTO_NAME
            value: {{ include "satpolpp.name" . }}-webhook
          - name: SATPOLPP_AUTO_HOST
            value: "{{ include "satpolpp.name" . }},{{ include "satpolpp.name" . }}.{{ .Release.Namespace }},{{ include "satpolpp.name" . }}.{{ .Release.Namespace }}.svc"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTPS
          failureThreshold: 2
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTPS
          failureThreshold: 2
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 5    
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
