---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "satpolpp.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "satpolpp.name" . }}
    helm.sh/chart: {{ include "satpolpp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
webhooks:
  - name: deploymentcheck-satpolpp.imrenagi.com
    clientConfig:
      caBundle: {{ .Values.certs.caBundle }}
      service:
        name: {{ include "satpolpp.name" . }}
        namespace: {{ .Release.Namespace }}
        path: "/deployments/check"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
        scope: "Namespaced"
    namespaceSelector: {}
  - name: configmapcheck-satpolpp.imrenagi.com
    clientConfig:
      caBundle: {{ .Values.certs.caBundle }}
      service:
        name: {{ include "satpolpp.name" . }}
        namespace: {{ .Release.Namespace }}
        path: "/configmaps/check"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["configmaps"]
        scope: "Namespaced"
    namespaceSelector: {}    