apiVersion: v1
kind: Service
metadata:
  name: {{ include "satpolpp.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "satpolpp.name" . }}
    helm.sh/chart: {{ include "satpolpp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "satpolpp.name" . }}    
    app.kubernetes.io/instance: {{ .Release.Name }}    
